CREATE DATABASE IF NOT EXISTS cakelicker_database;
USE cakelicker_database;

CREATE TABLE IF NOT EXISTS saves (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT "Desconhecido",
    cakes_coefficient INT(11) NOT NULL DEFAULT 0,
    cakes_exponent INT(11) NOT NULL DEFAULT 0,
    xp INT(11) NOT NULL DEFAULT 0,
    level INT(11) NOT NULL DEFAULT 1,
    prestige INT(11) NOT NULL DEFAULT 0,
    rebirths INT(11) NOT NULL DEFAULT 0,
    savepath VARCHAR(255) NOT NULL,
    creationdate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    saveid INT(11) NOT NULL,
    birthdate DATE NOT NULL,
    creationdate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (saveid) REFERENCES saves(id)
);

CREATE TABLE IF NOT EXISTS sessions (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    userid INT(11) NOT NULL,
    expiresat DATETIME NOT NULL,

    FOREIGN KEY (userid) REFERENCES users(id)
);